# Generated by Django 5.0.4 on 2024-06-01 15:17

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(default=users.models.create_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=512, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.delivery'),
            preserve_default=False,
        ),
    ]
