# Generated by Django 5.0.4 on 2024-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_order_state_remove_order_user_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
