# Generated by Django 5.0.4 on 2024-05-30 13:33

import django.db.models.deletion
import dress.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.CharField(default=dress.models.create_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DressColor',
            fields=[
                ('id', models.CharField(default=dress.models.create_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='dress.dress')),
            ],
        ),
        migrations.CreateModel(
            name='DressModel',
            fields=[
                ('id', models.CharField(default=dress.models.create_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='dress.dress')),
            ],
        ),
        migrations.CreateModel(
            name='DressSize',
            fields=[
                ('id', models.CharField(default=dress.models.create_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='dress.dress')),
            ],
        ),
    ]
